package com.entity.task;

import java.util.Date;

public class SysTaskLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_task_log.ID
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_task_log.READ_TABLE_NAME
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    private String readTableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_task_log.WRITE_TABLE_NAME
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    private String writeTableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_task_log.LASTEXCU_BEGINTIME
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    private Date lastexcuBegintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_task_log.LASTEXCU_ENDTIME
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    private Date lastexcuEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_task_log.REMARK
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_task_log.CREAT_TIME
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    private Date creatTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_task_log.ID
     *
     * @return the value of sys_task_log.ID
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_task_log.ID
     *
     * @param id the value for sys_task_log.ID
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_task_log.READ_TABLE_NAME
     *
     * @return the value of sys_task_log.READ_TABLE_NAME
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    public String getReadTableName() {
        return readTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_task_log.READ_TABLE_NAME
     *
     * @param readTableName the value for sys_task_log.READ_TABLE_NAME
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    public void setReadTableName(String readTableName) {
        this.readTableName = readTableName == null ? null : readTableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_task_log.WRITE_TABLE_NAME
     *
     * @return the value of sys_task_log.WRITE_TABLE_NAME
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    public String getWriteTableName() {
        return writeTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_task_log.WRITE_TABLE_NAME
     *
     * @param writeTableName the value for sys_task_log.WRITE_TABLE_NAME
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    public void setWriteTableName(String writeTableName) {
        this.writeTableName = writeTableName == null ? null : writeTableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_task_log.LASTEXCU_BEGINTIME
     *
     * @return the value of sys_task_log.LASTEXCU_BEGINTIME
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    public Date getLastexcuBegintime() {
        return lastexcuBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_task_log.LASTEXCU_BEGINTIME
     *
     * @param lastexcuBegintime the value for sys_task_log.LASTEXCU_BEGINTIME
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    public void setLastexcuBegintime(Date lastexcuBegintime) {
        this.lastexcuBegintime = lastexcuBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_task_log.LASTEXCU_ENDTIME
     *
     * @return the value of sys_task_log.LASTEXCU_ENDTIME
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    public Date getLastexcuEndtime() {
        return lastexcuEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_task_log.LASTEXCU_ENDTIME
     *
     * @param lastexcuEndtime the value for sys_task_log.LASTEXCU_ENDTIME
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    public void setLastexcuEndtime(Date lastexcuEndtime) {
        this.lastexcuEndtime = lastexcuEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_task_log.REMARK
     *
     * @return the value of sys_task_log.REMARK
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_task_log.REMARK
     *
     * @param remark the value for sys_task_log.REMARK
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_task_log.CREAT_TIME
     *
     * @return the value of sys_task_log.CREAT_TIME
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_task_log.CREAT_TIME
     *
     * @param creatTime the value for sys_task_log.CREAT_TIME
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }
}