package com.mapper.caseInfo;


import com.entity.caseInfo.ApScarela;

import java.util.Date;
import java.util.Map;

public interface ApScarelaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_scarela
     *
     * @mbggenerated Sat Feb 10 15:11:02 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_scarela
     *
     * @mbggenerated Sat Feb 10 15:11:02 CST 2018
     */
    int insert(ApScarela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_scarela
     *
     * @mbggenerated Sat Feb 10 15:11:02 CST 2018
     */
    int insertSelective(ApScarela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_scarela
     *
     * @mbggenerated Sat Feb 10 15:11:02 CST 2018
     */
    ApScarela selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_scarela
     *
     * @mbggenerated Sat Feb 10 15:11:02 CST 2018
     */
    int updateByPrimaryKeySelective(ApScarela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_scarela
     *
     * @mbggenerated Sat Feb 10 15:11:02 CST 2018
     */
    int updateByPrimaryKey(ApScarela record);

    Date selectMaxCreateTime();

    Date selectMaxUpdateTime();

    ApScarela findById(Map<String, Object> param);
}