package com.mapper.task.log;

import com.entity.task.SysTaskLog;

public interface SysTaskLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task_log
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task_log
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    int insert(SysTaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task_log
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    int insertSelective(SysTaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task_log
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    SysTaskLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task_log
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    int updateByPrimaryKeySelective(SysTaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task_log
     *
     * @mbggenerated Tue Mar 20 15:40:31 CST 2018
     */
    int updateByPrimaryKey(SysTaskLog record);

    SysTaskLog selectLastLogByTableName(String readTableName);
}